project_id = "zukmwqfqmfuyqpxfjqil"

[functions.api-v1]
verify_jwt = false

[functions.check-incomplete-trainings]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = true

[functions.send-feedback-email]
verify_jwt = true

[functions.submit-feedback]
verify_jwt = false

[functions.get-feedback-form]
verify_jwt = false
